ViewComponents/SidebarViewComponent.cs
using MasteryTest3.Data;
using MasteryTest3.Interfaces;
using MasteryTest3.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace MasteryTest3.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly IUserRepository _userRepository;
        private readonly IOrderService _orderService;
        private readonly ISessionService _sessionService;

        public SidebarViewComponent(IUserRepository userRepository, IOrderService orderService, ISessionService sessionService)
        {
            _userRepository = userRepository;
            _orderService = orderService;
            _sessionService = sessionService;
        }

        public async Task<IViewComponentResult> InvokeAsync() {

            var role = Request.Query["role"].ToString();
            var pendingApprovalCount = 0;
            var sessionUser = _sessionService.GetSessionUser();

            if (sessionUser.role.name != "requester") {
                var orders = await _orderService.GetAllOrders(OrderStatus.FOR_APPROVAL, Role.APPROVER);
                pendingApprovalCount = orders.Count();
            }

            var ViewModel = new SidebarViewModel()
            {
                users = await _userRepository.GetAllUsers(),
                pendingApprovalCount = pendingApprovalCount
            };

            return View("Default", ViewModel);
        }
    }
}

Views/Shared/_Layout.cshtml
@using MasteryTest3.Interfaces
@inject ISessionService sessionService;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MasteryTest</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@40,200,0,0" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MasteryTest3.styles.css" asp-append-version="true" />
</head>

<body class="d-flex flex-column">

    @if (sessionService.GetInt("userId") != null)
    {
        @await Component.InvokeAsync("Sidebar")
    }

    <div class="d-flex flex-column h-100" @(sessionService.GetInt("userId") != null ? "style=margin-left:260px" : "")>
        @RenderBody()
   </div>
  
   @await RenderSectionAsync("Scripts", required: false)
    
</body>

</html>

Views/Shared/_NavbarBack.cshtml
<div class="container mw-primary">
    <div class="navbar-nav d-flex flex-row align-items-center gap-3 mt-5">
        <a class="nav-link p-0" href="..">Back</a>
    </div>
</div>

Views/Shared/_NavbarMenu.cshtml
<div class="container mw-primary">
    <div class="navbar-nav d-flex flex-row align-items-center gap-3">
        <a class="nav-link p-0" href="@Url.Action("Index","Home")">Home</a>
    </div>
</div>